web_server: yes

tasks:
  test task:
    series:
      - Rick and Morty:
          begin: S02E01
    discover:
      what:
        - next_series_episodes:
            backfill: yes
      from:
        - torrentleech:
            rss_key: b09fa538a509e4762db0
            username: fenixes
            password: 356c992e#
    download: ~/downloads

schedules:
  # Run every 30 minutes
  - tasks: '*'
    schedule:
      minute: "*/20"
