#!/usr/bin/with-contenv bash

pip install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip install -U setuptools>=36
pip install -U urllib3[socks]
pip install -U chardet
pip install -U irc_bot
pip install -U cfscrape

# Install flexget last (it might force specific versions of other packages).
pip install -U flexget

pip install git+https://github.com/carlba/Flexget.git@feature/temp_use_torrentleach_v4_api