#!/usr/bin/with-contenv bash

pip install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip install -U setuptools>=36
pip install -U urllib3[socks]
pip install -U chardet
pip install -U irc_bot
pip install -U cfscrape

# Clone flexget source
cd /tmp
rm -rf Flexget
git clone -b feature/temp_use_torrentleech_v4_api  https://github.com/carlba/Flexget.git
cd Flexget

# Build flexget UI
apk add --update nodejs nodejs-npm g++ make && npm install -g bower && npm install -g gulp

cd flexget/ui/v1
npm install
bower update --allow-root
gulp build

# Install flexget
cd ../../..
python setup.py install